//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuanLyThuVien.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Management.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string btnAccount {
            get {
                return ResourceManager.GetString("btnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string btnAuthor {
            get {
                return ResourceManager.GetString("btnAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string btnBook {
            get {
                return ResourceManager.GetString("btnBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookType.
        /// </summary>
        internal static string btnBookType {
            get {
                return ResourceManager.GetString("btnBookType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow.
        /// </summary>
        internal static string btnBorrow {
            get {
                return ResourceManager.GetString("btnBorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc.
        /// </summary>
        internal static string btnEsc {
            get {
                return ResourceManager.GetString("btnEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string btnLogout {
            get {
                return ResourceManager.GetString("btnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string btnNew {
            get {
                return ResourceManager.GetString("btnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string btnNext {
            get {
                return ResourceManager.GetString("btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string btnPrevious {
            get {
                return ResourceManager.GetString("btnPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string btnPublish {
            get {
                return ResourceManager.GetString("btnPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader.
        /// </summary>
        internal static string btnReader {
            get {
                return ResourceManager.GetString("btnReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string btnReport {
            get {
                return ResourceManager.GetString("btnReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password.
        /// </summary>
        internal static string CantLogin {
            get {
                return ResourceManager.GetString("CantLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Password.
        /// </summary>
        internal static string chxShowPassword {
            get {
                return ResourceManager.GetString("chxShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit ?.
        /// </summary>
        internal static string ClosingNotification {
            get {
                return ResourceManager.GetString("ClosingNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection was cancelled.
        /// </summary>
        internal static string ConnectionWasCancelled {
            get {
                return ResourceManager.GetString("ConnectionWasCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill All Infomation.
        /// </summary>
        internal static string FillAllBlank {
            get {
                return ResourceManager.GetString("FillAllBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string function {
            get {
                return ResourceManager.GetString("function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Value Was Not Correct Format.
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string IsCanceled {
            get {
                return ResourceManager.GetString("IsCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find stored produce or disconnected.
        /// </summary>
        internal static string IsFaulted {
            get {
                return ResourceManager.GetString("IsFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string lblAmout {
            get {
                return ResourceManager.GetString("lblAmout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author ID.
        /// </summary>
        internal static string lblAuthorID {
            get {
                return ResourceManager.GetString("lblAuthorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Name.
        /// </summary>
        internal static string lblAuthorName {
            get {
                return ResourceManager.GetString("lblAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Code.
        /// </summary>
        internal static string lblBookCode {
            get {
                return ResourceManager.GetString("lblBookCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Name.
        /// </summary>
        internal static string lblBookName {
            get {
                return ResourceManager.GetString("lblBookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Type Code.
        /// </summary>
        internal static string lblBookTypeCode {
            get {
                return ResourceManager.GetString("lblBookTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Type ID.
        /// </summary>
        internal static string lblBookTypeID {
            get {
                return ResourceManager.GetString("lblBookTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Type.
        /// </summary>
        internal static string lblBookTypeName {
            get {
                return ResourceManager.GetString("lblBookTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow Date.
        /// </summary>
        internal static string lblBorrowDate {
            get {
                return ResourceManager.GetString("lblBorrowDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Connection.
        /// </summary>
        internal static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string lblDateOfBirth {
            get {
                return ResourceManager.GetString("lblDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string lblExport {
            get {
                return ResourceManager.GetString("lblExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string lblFromDate {
            get {
                return ResourceManager.GetString("lblFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string lblID {
            get {
                return ResourceManager.GetString("lblID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory ID.
        /// </summary>
        internal static string lblInventoryID {
            get {
                return ResourceManager.GetString("lblInventoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string lblNew {
            get {
                return ResourceManager.GetString("lblNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numberical Order.
        /// </summary>
        internal static string lblNumbericalOrder {
            get {
                return ResourceManager.GetString("lblNumbericalOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        internal static string lblPublishDate {
            get {
                return ResourceManager.GetString("lblPublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish ID.
        /// </summary>
        internal static string lblPublishID {
            get {
                return ResourceManager.GetString("lblPublishID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Name.
        /// </summary>
        internal static string lblPublishName {
            get {
                return ResourceManager.GetString("lblPublishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader ID.
        /// </summary>
        internal static string lblReaderID {
            get {
                return ResourceManager.GetString("lblReaderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Date.
        /// </summary>
        internal static string lblReturnDate {
            get {
                return ResourceManager.GetString("lblReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        internal static string lblRole {
            get {
                return ResourceManager.GetString("lblRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role ID.
        /// </summary>
        internal static string lblRoleID {
            get {
                return ResourceManager.GetString("lblRoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Details ID.
        /// </summary>
        internal static string lblTicketDetailsID {
            get {
                return ResourceManager.GetString("lblTicketDetailsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Management.
        /// </summary>
        internal static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string lblToDate {
            get {
                return ResourceManager.GetString("lblToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to logout?.
        /// </summary>
        internal static string LogoutNotification {
            get {
                return ResourceManager.GetString("LogoutNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open connection to database.
        /// </summary>
        internal static string OpenConnectionError {
            get {
                return ResourceManager.GetString("OpenConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Stock.
        /// </summary>
        internal static string OutOfStock {
            get {
                return ResourceManager.GetString("OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Page.
        /// </summary>
        internal static string PerPage {
            get {
                return ResourceManager.GetString("PerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date: .
        /// </summary>
        internal static string PublishDateColumn {
            get {
                return ResourceManager.GetString("PublishDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role ID.
        /// </summary>
        internal static string RoleID {
            get {
                return ResourceManager.GetString("RoleID", resourceCulture);
            }
        }
    }
}
